# Data Analysis with Python - freeCodeCamp Course

## Introduction to NumPy

In [3]:
import numpy as np

### Basic Numpy Arrays

In [4]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
b = np.array([1.5, 3., 6.1, 2])
b

array([1.5, 3. , 6.1, 2. ])

In [7]:
a[1], a[3]

(2, 4)

In [8]:
a[1:3]

array([2, 3])

In [12]:
a[::-1]

array([4, 3, 2, 1])

In [13]:
a[[3, 0, 1]]

array([4, 1, 2])

### Array Types

In [14]:
a.dtype

dtype('int64')

In [18]:
b.dtype

dtype('float64')

### Dimensions and shapes

In [17]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
A.shape

(2, 3)

In [20]:
A.ndim

2

In [21]:
A.size

6

### Indexing and Slicing

In [23]:
# Square matrix
B = np.array([
# d2 0  1  2    d1
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [25]:
B[0]

array([1, 2, 3])

In [26]:
B[2,2]

9

In [28]:
B[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
B[0] = np.array([3,2,1])
B

array([[3, 2, 1],
       [4, 5, 6],
       [7, 8, 9]])

### Summary statistics

In [31]:
a.sum()

10

In [32]:
a.mean()

2.5

In [33]:
a.std()

1.118033988749895

In [34]:
a.var()

1.25

In [35]:
A.sum()

21

In [36]:
A.mean()

3.5

In [37]:
# sum each column
A.sum(axis=0)

array([5, 7, 9])

In [38]:
# mean of each row
A.mean(axis=1)

array([2., 5.])

In [40]:
A[0].sum()

6

### Vectorized operations

In [44]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [45]:
c + 10

array([10, 11, 12, 13, 14, 15])

In [46]:
c * 10

array([ 0, 10, 20, 30, 40, 50])

In [47]:
c += 1
c

array([1, 2, 3, 4, 5, 6])

In [49]:
d = np.arange(6)
d *= 10
d

array([ 0, 10, 20, 30, 40, 50])

In [50]:
c + d

array([ 1, 12, 23, 34, 45, 56])

In [51]:
c * d

array([  0,  20,  60, 120, 200, 300])

### Boolean arrays

In [52]:
a

array([1, 2, 3, 4])

In [53]:
# select values based on index
a[[0,-1]]

array([1, 4])

In [54]:
# select values based on boolean
a[[True, False, False, True]]

array([1, 4])

In [55]:
a > 2

array([False, False,  True,  True])

In [57]:
a[a>2]

array([3, 4])

In [58]:
a[ a > a.mean() ]

array([3, 4])

In [59]:
a[ (a == 1) | (a == 4) ]

array([1, 4])

In [62]:
C = np.random.randint(100, size=(4, 4))
C

array([[83, 67, 63, 98],
       [31, 82, 96,  0],
       [82, 32, 96, 49],
       [56, 41, 33, 56]])

In [63]:
C > 50

array([[ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True, False,  True, False],
       [ True, False, False,  True]])

In [64]:
C[C>50]

array([83, 67, 63, 98, 82, 96, 82, 96, 56, 56])